export const catalogConstants = {
  CATALOG_LIST_REQUEST: 'CATALOG_LIST_REQUEST',
  CATALOG_LIST_SUCCESS: 'CATALOG_LIST_SUCCESS',
  CATALOG_LIST_FAILURE: 'CATALOG_LIST_FAILURE',
  CLEAR_ERROR: 'CLEAR_ERROR',
};
